#include <goose/planner/operator/logical_aggregate.h>
#include <goose/planner/operator/logical_any_join.h>
#include <goose/planner/operator/logical_column_data_get.h>
#include <goose/planner/operator/logical_comparison_join.h>
#include <goose/planner/operator/logical_dependent_join.h>
#include <goose/planner/operator/logical_copy_database.h>
#include <goose/planner/operator/logical_copy_to_file.h>
#include <goose/planner/operator/logical_create.h>
#include <goose/planner/operator/logical_create_index.h>
#include <goose/planner/operator/logical_create_table.h>
#include <goose/planner/operator/logical_create_secret.h>
#include <goose/planner/operator/logical_cross_product.h>
#include <goose/planner/operator/logical_cte.h>
#include <goose/planner/operator/logical_cteref.h>
#include <goose/planner/operator/logical_delete.h>
#include <goose/planner/operator/logical_delim_get.h>
#include <goose/planner/operator/logical_distinct.h>
#include <goose/planner/operator/logical_dummy_scan.h>
#include <goose/planner/operator/logical_empty_result.h>
#include <goose/planner/operator/logical_execute.h>
#include <goose/planner/operator/logical_explain.h>
#include <goose/planner/operator/logical_export.h>
#include <goose/planner/operator/logical_expression_get.h>
#include <goose/planner/operator/logical_extension_operator.h>
#include <goose/planner/operator/logical_filter.h>
#include <goose/planner/operator/logical_get.h>
#include <goose/planner/operator/logical_insert.h>
#include <goose/planner/operator/logical_join.h>
#include <goose/planner/operator/logical_limit.h>
#include <goose/planner/operator/logical_materialized_cte.h>
#include <goose/planner/operator/logical_merge_into.h>
#include <goose/planner/operator/logical_order.h>
#include <goose/planner/operator/logical_pivot.h>
#include <goose/planner/operator/logical_positional_join.h>
#include <goose/planner/operator/logical_pragma.h>
#include <goose/planner/operator/logical_prepare.h>
#include <goose/planner/operator/logical_projection.h>
#include <goose/planner/operator/logical_recursive_cte.h>
#include <goose/planner/operator/logical_reset.h>
#include <goose/planner/operator/logical_sample.h>
#include <goose/planner/operator/logical_set.h>
#include <goose/planner/operator/logical_set_operation.h>
#include <goose/planner/operator/logical_simple.h>
#include <goose/planner/operator/logical_top_n.h>
#include <goose/planner/operator/logical_unnest.h>
#include <goose/planner/operator/logical_update.h>
#include <goose/planner/operator/logical_vacuum.h>
#include <goose/planner/operator/logical_window.h>
