#include <goose/parser/statement/alter_statement.h>
#include <goose/parser/statement/attach_statement.h>
#include <goose/parser/statement/call_statement.h>
#include <goose/parser/statement/copy_statement.h>
#include <goose/parser/statement/copy_database_statement.h>
#include <goose/parser/statement/create_statement.h>
#include <goose/parser/statement/delete_statement.h>
#include <goose/parser/statement/detach_statement.h>
#include <goose/parser/statement/drop_statement.h>
#include <goose/parser/statement/execute_statement.h>
#include <goose/parser/statement/explain_statement.h>
#include <goose/parser/statement/extension_statement.h>
#include <goose/parser/statement/export_statement.h>
#include <goose/parser/statement/insert_statement.h>
#include <goose/parser/statement/load_statement.h>
#include <goose/parser/statement/logical_plan_statement.h>
#include <goose/parser/statement/merge_into_statement.h>
#include <goose/parser/statement/pragma_statement.h>
#include <goose/parser/statement/prepare_statement.h>
#include <goose/parser/statement/relation_statement.h>
#include <goose/parser/statement/select_statement.h>
#include <goose/parser/statement/set_statement.h>
#include <goose/parser/statement/transaction_statement.h>
#include <goose/parser/statement/update_statement.h>
#include <goose/parser/statement/update_extensions_statement.h>
#include <goose/parser/statement/vacuum_statement.h>
