#include <goose/function/function_list.h>

#include <goose/function/aggregate/distributive_functions.h>
#include <goose/function/scalar/compressed_materialization_functions.h>
#include <goose/function/scalar/date_functions.h>
#include <goose/function/scalar/generic_functions.h>
#include <goose/function/scalar/geometry_functions.h>
#include <goose/function/scalar/list_functions.h>
#include <goose/function/scalar/map_functions.h>
#include <goose/function/scalar/variant_functions.h>
#include <goose/function/scalar/operator_functions.h>
#include <goose/function/scalar/sequence_functions.h>
#include <goose/function/scalar/string_functions.h>
#include <goose/function/scalar/struct_functions.h>
#include <goose/function/scalar/system_functions.h>
#include <goose/parser/parsed_data/create_aggregate_function_info.h>
#include <goose/parser/parsed_data/create_scalar_function_info.h>


namespace goose {

// Scalar Function
#define GOOSE_SCALAR_FUNCTION_BASE(_PARAM, _NAME, _ALIAS_OF)                                                                     \
	{ _NAME, _ALIAS_OF, _PARAM::Parameters, _PARAM::Description, _PARAM::Example, _PARAM::Categories, _PARAM::GetFunction, nullptr, nullptr, nullptr }
#define GOOSE_SCALAR_FUNCTION(_PARAM)       GOOSE_SCALAR_FUNCTION_BASE(_PARAM, _PARAM::Name, _PARAM::Name)
#define GOOSE_SCALAR_FUNCTION_ALIAS(_PARAM) GOOSE_SCALAR_FUNCTION_BASE(_PARAM::ALIAS, _PARAM::Name, _PARAM::ALIAS::Name)
// Scalar Function Set
#define GOOSE_SCALAR_FUNCTION_SET_BASE(_PARAM, _NAME, _ALIAS_OF)                                                                 \
	{ _NAME, _ALIAS_OF, _PARAM::Parameters, _PARAM::Description, _PARAM::Example, _PARAM::Categories, nullptr, _PARAM::GetFunctions, nullptr, nullptr }
#define GOOSE_SCALAR_FUNCTION_SET(_PARAM)       GOOSE_SCALAR_FUNCTION_SET_BASE(_PARAM, _PARAM::Name, _PARAM::Name)
#define GOOSE_SCALAR_FUNCTION_SET_ALIAS(_PARAM) GOOSE_SCALAR_FUNCTION_SET_BASE(_PARAM::ALIAS, _PARAM::Name, _PARAM::ALIAS::Name)
// Aggregate Function
#define GOOSE_AGGREGATE_FUNCTION_BASE(_PARAM, _NAME, _ALIAS_OF)                                                                  \
	{ _NAME, _ALIAS_OF, _PARAM::Parameters, _PARAM::Description, _PARAM::Example, _PARAM::Categories, nullptr, nullptr, _PARAM::GetFunction, nullptr }
#define GOOSE_AGGREGATE_FUNCTION(_PARAM)       GOOSE_AGGREGATE_FUNCTION_BASE(_PARAM, _PARAM::Name, _PARAM::Name)
#define GOOSE_AGGREGATE_FUNCTION_ALIAS(_PARAM) GOOSE_AGGREGATE_FUNCTION_BASE(_PARAM::ALIAS, _PARAM::Name, _PARAM::ALIAS::Name)
// Aggregate Function Set
#define GOOSE_AGGREGATE_FUNCTION_SET_BASE(_PARAM, _NAME, _ALIAS_OF)                                                              \
	{ _NAME, _ALIAS_OF, _PARAM::Parameters, _PARAM::Description, _PARAM::Example, _PARAM::Categories, nullptr, nullptr, nullptr, _PARAM::GetFunctions }
#define GOOSE_AGGREGATE_FUNCTION_SET(_PARAM)       GOOSE_AGGREGATE_FUNCTION_SET_BASE(_PARAM, _PARAM::Name, _PARAM::Name)
#define GOOSE_AGGREGATE_FUNCTION_SET_ALIAS(_PARAM) GOOSE_AGGREGATE_FUNCTION_SET_BASE(_PARAM::ALIAS, _PARAM::Name, _PARAM::ALIAS::Name)
#define FINAL_FUNCTION                                                                                                 \
	{ nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr }

// this list is generated by scripts/generate_functions.py
static const StaticFunctionDefinition function[] = {
	GOOSE_SCALAR_FUNCTION(NotLikeFun),
	GOOSE_SCALAR_FUNCTION(NotILikeFun),
	GOOSE_SCALAR_FUNCTION_SET(OperatorModuloFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(StIntersectsExtentFunAlias),
	GOOSE_SCALAR_FUNCTION_SET(OperatorMultiplyFun),
	GOOSE_SCALAR_FUNCTION_SET(OperatorAddFun),
	GOOSE_SCALAR_FUNCTION_SET(OperatorSubtractFun),
	GOOSE_SCALAR_FUNCTION_SET(OperatorFloatDivideFun),
	GOOSE_SCALAR_FUNCTION_SET(OperatorIntegerDivideFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalCompressIntegralUbigintFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalCompressIntegralUintegerFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalCompressIntegralUsmallintFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalCompressIntegralUtinyintFun),
	GOOSE_SCALAR_FUNCTION(InternalCompressStringHugeintFun),
	GOOSE_SCALAR_FUNCTION(InternalCompressStringUbigintFun),
	GOOSE_SCALAR_FUNCTION(InternalCompressStringUhugeintFun),
	GOOSE_SCALAR_FUNCTION(InternalCompressStringUintegerFun),
	GOOSE_SCALAR_FUNCTION(InternalCompressStringUsmallintFun),
	GOOSE_SCALAR_FUNCTION(InternalCompressStringUtinyintFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalDecompressIntegralBigintFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalDecompressIntegralHugeintFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalDecompressIntegralIntegerFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalDecompressIntegralSmallintFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalDecompressIntegralUbigintFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalDecompressIntegralUhugeintFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalDecompressIntegralUintegerFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalDecompressIntegralUsmallintFun),
	GOOSE_SCALAR_FUNCTION_SET(InternalDecompressStringFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(AddFun),
	GOOSE_AGGREGATE_FUNCTION_SET(AnyValueFun),
	GOOSE_AGGREGATE_FUNCTION_SET_ALIAS(ArbitraryFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArrayCatFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArrayConcatFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArrayContainsFun),
	GOOSE_SCALAR_FUNCTION_SET(ArrayExtractFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArrayHasFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArrayIndexofFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArrayIntersectFun),
	GOOSE_SCALAR_FUNCTION_SET(ArrayLengthFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArrayPositionFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(ArrayResizeFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArraySelectFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArrayWhereFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ArrayZipFun),
	GOOSE_SCALAR_FUNCTION_SET(BitLengthFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(CharLengthFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(CharacterLengthFun),
	GOOSE_SCALAR_FUNCTION(CombineFun),
	GOOSE_SCALAR_FUNCTION(ConcatFun),
	GOOSE_SCALAR_FUNCTION(ConcatWsFun),
	GOOSE_SCALAR_FUNCTION(ConstantOrNullFun),
	GOOSE_SCALAR_FUNCTION_SET(ContainsFun),
	GOOSE_AGGREGATE_FUNCTION_SET(CountFun),
	GOOSE_AGGREGATE_FUNCTION(CountStarFun),
	GOOSE_SCALAR_FUNCTION(CreateSortKeyFun),
	GOOSE_SCALAR_FUNCTION(CurrentConnectionId),
	GOOSE_SCALAR_FUNCTION(CurrentQueryId),
	GOOSE_SCALAR_FUNCTION(CurrentTransactionId),
	GOOSE_SCALAR_FUNCTION(CurrvalFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(DivideFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(EndsWithFun),
	GOOSE_SCALAR_FUNCTION(ErrorFun),
	GOOSE_SCALAR_FUNCTION(FinalizeFun),
	GOOSE_AGGREGATE_FUNCTION_SET(FirstFun),
	GOOSE_SCALAR_FUNCTION(GetVariableFun),
	GOOSE_SCALAR_FUNCTION(IlikeEscapeFun),
	GOOSE_AGGREGATE_FUNCTION_SET(LastFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(LcaseFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(LenFun),
	GOOSE_SCALAR_FUNCTION_SET(LengthFun),
	GOOSE_SCALAR_FUNCTION_SET(LengthGraphemeFun),
	GOOSE_SCALAR_FUNCTION(LikeEscapeFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ListCatFun),
	GOOSE_SCALAR_FUNCTION(ListConcatFun),
	GOOSE_SCALAR_FUNCTION(ListContainsFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(ListElementFun),
	GOOSE_SCALAR_FUNCTION_SET(ListExtractFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ListHasFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(ListIndexofFun),
	GOOSE_SCALAR_FUNCTION(ListIntersectFun),
	GOOSE_SCALAR_FUNCTION(ListPositionFun),
	GOOSE_SCALAR_FUNCTION_SET(ListResizeFun),
	GOOSE_SCALAR_FUNCTION(ListSelectFun),
	GOOSE_SCALAR_FUNCTION(ListWhereFun),
	GOOSE_SCALAR_FUNCTION(ListZipFun),
	GOOSE_SCALAR_FUNCTION(LowerFun),
	GOOSE_SCALAR_FUNCTION(MapContainsFun),
	GOOSE_AGGREGATE_FUNCTION_SET(MaxFun),
	GOOSE_SCALAR_FUNCTION_SET(MD5Fun),
	GOOSE_SCALAR_FUNCTION_SET(MD5NumberFun),
	GOOSE_AGGREGATE_FUNCTION_SET(MinFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(ModFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(MultiplyFun),
	GOOSE_SCALAR_FUNCTION(NextvalFun),
	GOOSE_SCALAR_FUNCTION(NFCNormalizeFun),
	GOOSE_SCALAR_FUNCTION(NotIlikeEscapeFun),
	GOOSE_SCALAR_FUNCTION(NotLikeEscapeFun),
	GOOSE_SCALAR_FUNCTION_SET(OctetLengthFun),
	GOOSE_SCALAR_FUNCTION(ParseLogMessage),
	GOOSE_SCALAR_FUNCTION(PrefixFun),
	GOOSE_SCALAR_FUNCTION(RegexpEscapeFun),
	GOOSE_SCALAR_FUNCTION_SET(RegexpExtractFun),
	GOOSE_SCALAR_FUNCTION_SET(RegexpExtractAllFun),
	GOOSE_SCALAR_FUNCTION_SET(RegexpFun),
	GOOSE_SCALAR_FUNCTION_SET(RegexpMatchesFun),
	GOOSE_SCALAR_FUNCTION_SET(RegexpReplaceFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(RegexpSplitToArrayFun),
	GOOSE_SCALAR_FUNCTION(RemapStructFun),
	GOOSE_SCALAR_FUNCTION(RowFun),
	GOOSE_SCALAR_FUNCTION_SET(SHA1Fun),
	GOOSE_SCALAR_FUNCTION_SET(SHA256Fun),
	GOOSE_SCALAR_FUNCTION_ALIAS(SplitFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(StAsbinaryFun),
	GOOSE_SCALAR_FUNCTION(StAstextFun),
	GOOSE_SCALAR_FUNCTION(StAswkbFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(StAswktFun),
	GOOSE_SCALAR_FUNCTION(StCrsFun),
	GOOSE_SCALAR_FUNCTION(StGeomfromwkbFun),
	GOOSE_SCALAR_FUNCTION(StIntersectsExtentFun),
	GOOSE_SCALAR_FUNCTION(StSetcrsFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(StrSplitFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(StrSplitRegexFun),
	GOOSE_SCALAR_FUNCTION_SET(StrfTimeFun),
	GOOSE_SCALAR_FUNCTION(StringSplitFun),
	GOOSE_SCALAR_FUNCTION_SET(StringSplitRegexFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(StringToArrayFun),
	GOOSE_SCALAR_FUNCTION(StripAccentsFun),
	GOOSE_SCALAR_FUNCTION(StrlenFun),
	GOOSE_SCALAR_FUNCTION_SET(StrpTimeFun),
	GOOSE_SCALAR_FUNCTION(StructConcatFun),
	GOOSE_SCALAR_FUNCTION(StructContainsFun),
	GOOSE_SCALAR_FUNCTION_SET(StructExtractFun),
	GOOSE_SCALAR_FUNCTION(StructExtractAtFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(StructHasFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(StructIndexofFun),
	GOOSE_SCALAR_FUNCTION(StructPackFun),
	GOOSE_SCALAR_FUNCTION(StructPositionFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(SubstrFun),
	GOOSE_SCALAR_FUNCTION_SET(SubstringFun),
	GOOSE_SCALAR_FUNCTION_SET(SubstringGraphemeFun),
	GOOSE_SCALAR_FUNCTION_SET_ALIAS(SubtractFun),
	GOOSE_SCALAR_FUNCTION(SuffixFun),
	GOOSE_SCALAR_FUNCTION_SET(TryStrpTimeFun),
	GOOSE_SCALAR_FUNCTION_ALIAS(UcaseFun),
	GOOSE_SCALAR_FUNCTION(UpperFun),
	GOOSE_SCALAR_FUNCTION_SET(VariantExtractFun),
	GOOSE_SCALAR_FUNCTION(VariantNormalizeFun),
	GOOSE_SCALAR_FUNCTION(VariantTypeofFun),
	GOOSE_SCALAR_FUNCTION_SET(WriteLogFun),
	GOOSE_SCALAR_FUNCTION(ConcatOperatorFun),
	GOOSE_SCALAR_FUNCTION(LikeFun),
	GOOSE_SCALAR_FUNCTION(ILikeFun),
	GOOSE_SCALAR_FUNCTION(GlobPatternFun),
	FINAL_FUNCTION
};

const StaticFunctionDefinition *FunctionList::GetInternalFunctionList() {
	return function;
}

} // namespace goose
