//===----------------------------------------------------------------------===//
//                         Goose
//
// core_functions/scalar/debug_functions.h
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include <goose/function/function_set.h>

namespace goose {

struct VectorTypeFun {
	static constexpr const char *Name = "vector_type";
	static constexpr const char *Parameters = "col";
	static constexpr const char *Description = "Returns the VectorType of a given column";
	static constexpr const char *Example = "vector_type(col)";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

struct SleepMsFun {
	static constexpr const char *Name = "sleep_ms";
	static constexpr const char *Parameters = "milliseconds";
	static constexpr const char *Description = "Sleeps for the specified number of milliseconds and returns NULL";
	static constexpr const char *Example = "sleep_ms(100)";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

} // namespace goose
